/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window2DLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_EDIT_0    (GUI_ID_USER + 0x04)
#define ID_TEXT_0    (GUI_ID_USER + 0x05)

// USER START (Optionally insert additional defines)
extern RTC_HandleTypeDef hrtc;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window2", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 72, 20, 80, 53, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 161, 22, 80, 53, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 9, 93, 299, 130, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 149, 26, 17, 46, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;


  // USER START (Optionally insert additional variables)
  RTC_TimeTypeDef sTime;
  RTC_DateTypeDef sDate;
  uint8_t time_Text[8];
  static  float value_sensor_temp_OW[20];

  WM_HTIMER hTimer1;
  WM_HWIN hbut0;
  WM_HWIN hbut1;
  static uint8_t count;
 static uint8_t count_time;
  // USER END

  switch (pMsg->MsgId) {


  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window2'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x0080FF80));

    //
    // Initialization of 'Edit'
    //
   // hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);

    // USER START (Optionally insert additional code for further widget initialization)

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
            BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    hTimer1 = WM_CreateTimer(pMsg->hWin, 0, 100, 0);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
       TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
       TEXT_SetText(hItem, " ");
       TEXT_SetFont(hItem, &GUI_Font32B_ASCII);
   // hbut0=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);

    // USER END
    break;
  case WM_TIMER:

	  if(count==0)
	  {
	  	 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	  	 TEXT_SetText(hItem,":");
	  	 count++;

	  }else
	  {
	  if(count==1)
	  {
	  	 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	  	 TEXT_SetText(hItem," ");
	  	 count=0;
	  }

	  	 }

	  if(count_time==4)
	  {

		 Get_tem_sensor_OW(&value_sensor_temp_OW);
		  count_time=0;
	  }else
	  {
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	//  BUTTON_SetFont(hItem,&GUI_Font32_1);
  	  //hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
  	      	  HAL_RTC_GetTime(&hrtc,&sTime,RTC_FORMAT_BIN);
  	      	  HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);
  	      	// sprintf(&time_Text,"%02d %02d",sTime.Hours,sTime.Minutes);
  	      	sprintf(&time_Text,"%02d" ,sTime.Hours);
  	      	// EDIT_SetText(hItem, time_Text);
  	      	BUTTON_SetText(hItem,time_Text);
  	      sprintf(&time_Text,"%02d" ,sTime.Minutes);
  	   hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
  	 // BUTTON_SetFont(hItem,&GUI_Font32_1);
  	  BUTTON_SetText(hItem,time_Text);

  	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
  	sprintf(time_Text, "sensor1  - temperature %d C \r\n   " , (uint8_t)value_sensor_temp_OW[0]);
  	sprintf(time_Text, "sensor2  - temperature %d C    " , (uint8_t)value_sensor_temp_OW[1]);


  	EDIT_SetText(hItem, time_Text);
  	 count_time++;

	  }
  	      	WM_RestartTimer(pMsg->Data.v, 500);
  	  break;

  	   case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    	          BUTTON_SetBkColor(hItem, 0, GUI_RED);
    	  // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

    	  // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    	     // WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00aa00));
    	  EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_RED);
    	  // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    	     EDIT_SetText(hItem, "444");
    	  // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow2
*/
WM_HWIN CreateWindow2(void);
WM_HWIN CreateWindow2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
